# included templates
include:
  - 'https://gitlab.com/senbox-org/snap-engine/raw/9.0.6-reference/.gitlab-ci.yml'

mvn-build:
  image: "registry.hub.docker.com/library/maven:3.9.1-eclipse-temurin-8"
  artifacts:
    paths:
      - "${MAVEN_PROJECT_DIR}/**/target/*.jar"
      - "${MAVEN_PROJECT_DIR}/**/target/classes"
      - "${MAVEN_PROJECT_DIR}/**/target/*.nbm"
      - "${MAVEN_PROJECT_DIR}/s3tbx-kit/target"
      - "${MAVEN_PROJECT_DIR}/target"