dist: xenial

language: java

jdk:
  - openjdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "bEawyN0EOPErOSLjQ3UkjbZGKFBQL+3XrDM7y5HAPqxt39+o8KOR1dshMrRsgHnYmzzDDh1gP8eW3+nObY0qy4KZrYJCU+7/4we91ABM6coexSiv0CFn4s6vhr+5q+4pWGJSvoQxZV3uO36HCtSNfhlNDn5oEaQgwdqjy5QigrA="

addons:
  coverity_scan:
    project:
      name: "senbox-org/s3tbx"
      description: "Build submitted via Travis CI"
    notification_email: stb-coverity@thor.si.c-s.fr
    # build_command_prepend: ""
    build_command: "mvn -DskipTests=true clean compile"
    branch_pattern: coverity_scan

script:
  - mvn clean install -B -V
